version: '3'
services:
    web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: <dir-in-container>
    volumes:
    — .:/<dir-in-container>
    ports:
    — "8000:8000" 