# Generated by Django 3.0.7 on 2020-09-07 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_post_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
    ]
