name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DEBUG:  ${{ secret.DEBUG }}
        SECRET_KEY: ${{ secret.SECRET_KEY }}
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
