name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo DEBUG=${{ secrets.DEBUG }} >> .env
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
